### ISSUE TITLE
This tool is one way conversion only for ctxb.

### ISSUE THREAD

**Issue by Metafalica** [xdanieldzd/Tharsis#1]
Hello.
Is it possible for you to make conversion from png or gif to ctxb?
One way conversion is good, unless someone want to translate the game into native language and have no tools for changing the graphics :/
We are translating Zelda Ocarina of Time 3D and Majora's Mask 3D and kinda no want to release the translation without translated graphics.
I though since you already worked with this format, it will be easer for you to make the converter.
Thank you.

**Comment by xdanieldzd** [comment]
Converting _to_ any of the formats supported for converting _from_, such as CTXB, isn't really in the scope of this program. It is mainly meant for getting resources and assets out of a game, not for inserting them into it.

I could theoretically try my hand at writing a dedicated PNG/GIF/BMP/etc. to CTXB converter - it would certainly be an interesting challenge - but I don't really have the free time for this at the moment.

**Comment by Metafalica** [comment]
Thank you, buy the way you also can help by providing ctxb file documentation. Maybe you have time for that. I am also programmer, but it really hard to understand file structure just by some program sources.

**Comment by xdanieldzd** [comment]
Adding support for conversion of ex. PNGs **to** STEX and CTXB is now planned, as the underlying conversion code has since been rewritten and does support encoding images. See issue #2.
